
version: '3.9'

services:

  data:

    image: mysql:8-oracle
    container_name: 'todos-data'

    restart: unless-stopped

    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE

    volumes:
      - db:/var/lib/mysql

  app:

    depends_on:
      - data

    build: ./todos-app

    image: 'todos-app:1.0.0'
    container_name: 'todos-app'

    restart: on-failure

    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT

    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://data:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect"
          }'

    stdin_open: true
    tty: true

volumes:
  db:
